# fly.toml app configuration file generated for 8amcoffee on 2026-06-07T10:23:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '8amcoffee'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 150
    soft_limit = 100

  [[http_service.checks]]
    interval = '20s'
    timeout = '10s'
    grace_period = '40s'
    method = 'GET'
    path = '/login'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
